(dolist (mode '(c-mode c++-mode))
  (evil-leader/set-key-for-mode mode
    "m ." 'rtags-find-symbol-at-point
    "m ," 'rtags-find-references-at-point
    "m v" 'rtags-find-virtuals-at-point
    "m V" 'rtags-print-enum-value-at-point
    "m /" 'rtags-find-all-references-at-point
    "m Y" 'rtags-cycle-overlays-on-screen
    "m >" 'rtags-find-symbol
    "m <" 'rtags-find-references
    "m [" 'rtags-location-stack-back
    "m ]" 'rtags-location-stack-forward
    "m D" 'rtags-diagnostics
    "m G" 'rtags-guess-function-at-point
    "m p" 'rtags-set-current-project
    "m P" 'rtags-print-dependencies
    "m e" 'rtags-reparse-file
    "m E" 'rtags-preprocess-file
    "m R" 'rtags-rename-symbol
    "m M" 'rtags-symbol-info
    "m S" 'rtags-display-summary
    "m O" 'rtags-goto-offset
    "m ;" 'rtags-find-file
    "m F" 'rtags-fixit
    "m L" 'rtags-copy-and-print-current-location
    "m X" 'rtags-fix-fixit-at-point
    "m B" 'rtags-show-rtags-buffer
    "m I" 'rtags-imenu
    "m T" 'rtags-taglist
    "m h" 'rtags-print-class-hierarchy
    "m a" 'rtags-print-source-arguments))
